/*
  # Seed DND DC Master Items

  ## Overview
  Adds 362 DND DC gel polish master items to the global inventory catalog.
  The trigger `auto_create_store_inventory_levels` will automatically create
  per-store entries for all active stores.

  ## Items Breakdown
  - DND DC Original 001-144  (144 items)
  - DND DC Creamy  145-180   (36 items)
  - DND DC Expansion 181-326 (146 items)
  - DND DC Sheer   2436-2471 (36 items)
  Total: 362 items

  ## Changes
  1. Inserts 362 master items with brand = 'DND', category = 'Polish'
  2. ON CONFLICT (name) DO NOTHING for idempotency
*/

-- ============================================================================
-- DND DC Original Series (001-144)
-- ============================================================================
INSERT INTO public.inventory_items (name, category, unit, brand, is_master_item) VALUES
  ('DND DC Original 001', 'Polish', 'bottle', 'DND', true),
  ('DND DC Original 002', 'Polish', 'bottle', 'DND', true),
  ('DND DC Original 003', 'Polish', 'bottle', 'DND', true),
  ('DND DC Original 004', 'Polish', 'bottle', 'DND', true),
  ('DND DC Original 005', 'Polish', 'bottle', 'DND', true),
  ('DND DC Original 006', 'Polish', 'bottle', 'DND', true),
  ('DND DC Original 007', 'Polish', 'bottle', 'DND', true),
  ('DND DC Original 008', 'Polish', 'bottle', 'DND', true),
  ('DND DC Original 009', 'Polish', 'bottle', 'DND', true),
  ('DND DC Original 010', 'Polish', 'bottle', 'DND', true),
  ('DND DC Original 011', 'Polish', 'bottle', 'DND', true),
  ('DND DC Original 012', 'Polish', 'bottle', 'DND', true),
  ('DND DC Original 013', 'Polish', 'bottle', 'DND', true),
  ('DND DC Original 014', 'Polish', 'bottle', 'DND', true),
  ('DND DC Original 015', 'Polish', 'bottle', 'DND', true),
  ('DND DC Original 016', 'Polish', 'bottle', 'DND', true),
  ('DND DC Original 017', 'Polish', 'bottle', 'DND', true),
  ('DND DC Original 018', 'Polish', 'bottle', 'DND', true),
  ('DND DC Original 019', 'Polish', 'bottle', 'DND', true),
  ('DND DC Original 020', 'Polish', 'bottle', 'DND', true),
  ('DND DC Original 021', 'Polish', 'bottle', 'DND', true),
  ('DND DC Original 022', 'Polish', 'bottle', 'DND', true),
  ('DND DC Original 023', 'Polish', 'bottle', 'DND', true),
  ('DND DC Original 024', 'Polish', 'bottle', 'DND', true),
  ('DND DC Original 025', 'Polish', 'bottle', 'DND', true),
  ('DND DC Original 026', 'Polish', 'bottle', 'DND', true),
  ('DND DC Original 027', 'Polish', 'bottle', 'DND', true),
  ('DND DC Original 028', 'Polish', 'bottle', 'DND', true),
  ('DND DC Original 029', 'Polish', 'bottle', 'DND', true),
  ('DND DC Original 030', 'Polish', 'bottle', 'DND', true),
  ('DND DC Original 031', 'Polish', 'bottle', 'DND', true),
  ('DND DC Original 032', 'Polish', 'bottle', 'DND', true),
  ('DND DC Original 033', 'Polish', 'bottle', 'DND', true),
  ('DND DC Original 034', 'Polish', 'bottle', 'DND', true),
  ('DND DC Original 035', 'Polish', 'bottle', 'DND', true),
  ('DND DC Original 036', 'Polish', 'bottle', 'DND', true),
  ('DND DC Original 037', 'Polish', 'bottle', 'DND', true),
  ('DND DC Original 038', 'Polish', 'bottle', 'DND', true),
  ('DND DC Original 039', 'Polish', 'bottle', 'DND', true),
  ('DND DC Original 040', 'Polish', 'bottle', 'DND', true),
  ('DND DC Original 041', 'Polish', 'bottle', 'DND', true),
  ('DND DC Original 042', 'Polish', 'bottle', 'DND', true),
  ('DND DC Original 043', 'Polish', 'bottle', 'DND', true),
  ('DND DC Original 044', 'Polish', 'bottle', 'DND', true),
  ('DND DC Original 045', 'Polish', 'bottle', 'DND', true),
  ('DND DC Original 046', 'Polish', 'bottle', 'DND', true),
  ('DND DC Original 047', 'Polish', 'bottle', 'DND', true),
  ('DND DC Original 048', 'Polish', 'bottle', 'DND', true),
  ('DND DC Original 049', 'Polish', 'bottle', 'DND', true),
  ('DND DC Original 050', 'Polish', 'bottle', 'DND', true),
  ('DND DC Original 051', 'Polish', 'bottle', 'DND', true),
  ('DND DC Original 052', 'Polish', 'bottle', 'DND', true),
  ('DND DC Original 053', 'Polish', 'bottle', 'DND', true),
  ('DND DC Original 054', 'Polish', 'bottle', 'DND', true),
  ('DND DC Original 055', 'Polish', 'bottle', 'DND', true),
  ('DND DC Original 056', 'Polish', 'bottle', 'DND', true),
  ('DND DC Original 057', 'Polish', 'bottle', 'DND', true),
  ('DND DC Original 058', 'Polish', 'bottle', 'DND', true),
  ('DND DC Original 059', 'Polish', 'bottle', 'DND', true),
  ('DND DC Original 060', 'Polish', 'bottle', 'DND', true),
  ('DND DC Original 061', 'Polish', 'bottle', 'DND', true),
  ('DND DC Original 062', 'Polish', 'bottle', 'DND', true),
  ('DND DC Original 063', 'Polish', 'bottle', 'DND', true),
  ('DND DC Original 064', 'Polish', 'bottle', 'DND', true),
  ('DND DC Original 065', 'Polish', 'bottle', 'DND', true),
  ('DND DC Original 066', 'Polish', 'bottle', 'DND', true),
  ('DND DC Original 067', 'Polish', 'bottle', 'DND', true),
  ('DND DC Original 068', 'Polish', 'bottle', 'DND', true),
  ('DND DC Original 069', 'Polish', 'bottle', 'DND', true),
  ('DND DC Original 070', 'Polish', 'bottle', 'DND', true),
  ('DND DC Original 071', 'Polish', 'bottle', 'DND', true),
  ('DND DC Original 072', 'Polish', 'bottle', 'DND', true),
  ('DND DC Original 073', 'Polish', 'bottle', 'DND', true),
  ('DND DC Original 074', 'Polish', 'bottle', 'DND', true),
  ('DND DC Original 075', 'Polish', 'bottle', 'DND', true),
  ('DND DC Original 076', 'Polish', 'bottle', 'DND', true),
  ('DND DC Original 077', 'Polish', 'bottle', 'DND', true),
  ('DND DC Original 078', 'Polish', 'bottle', 'DND', true),
  ('DND DC Original 079', 'Polish', 'bottle', 'DND', true),
  ('DND DC Original 080', 'Polish', 'bottle', 'DND', true),
  ('DND DC Original 081', 'Polish', 'bottle', 'DND', true),
  ('DND DC Original 082', 'Polish', 'bottle', 'DND', true),
  ('DND DC Original 083', 'Polish', 'bottle', 'DND', true),
  ('DND DC Original 084', 'Polish', 'bottle', 'DND', true),
  ('DND DC Original 085', 'Polish', 'bottle', 'DND', true),
  ('DND DC Original 086', 'Polish', 'bottle', 'DND', true),
  ('DND DC Original 087', 'Polish', 'bottle', 'DND', true),
  ('DND DC Original 088', 'Polish', 'bottle', 'DND', true),
  ('DND DC Original 089', 'Polish', 'bottle', 'DND', true),
  ('DND DC Original 090', 'Polish', 'bottle', 'DND', true),
  ('DND DC Original 091', 'Polish', 'bottle', 'DND', true),
  ('DND DC Original 092', 'Polish', 'bottle', 'DND', true),
  ('DND DC Original 093', 'Polish', 'bottle', 'DND', true),
  ('DND DC Original 094', 'Polish', 'bottle', 'DND', true),
  ('DND DC Original 095', 'Polish', 'bottle', 'DND', true),
  ('DND DC Original 096', 'Polish', 'bottle', 'DND', true),
  ('DND DC Original 097', 'Polish', 'bottle', 'DND', true),
  ('DND DC Original 098', 'Polish', 'bottle', 'DND', true),
  ('DND DC Original 099', 'Polish', 'bottle', 'DND', true),
  ('DND DC Original 100', 'Polish', 'bottle', 'DND', true),
  ('DND DC Original 101', 'Polish', 'bottle', 'DND', true),
  ('DND DC Original 102', 'Polish', 'bottle', 'DND', true),
  ('DND DC Original 103', 'Polish', 'bottle', 'DND', true),
  ('DND DC Original 104', 'Polish', 'bottle', 'DND', true),
  ('DND DC Original 105', 'Polish', 'bottle', 'DND', true),
  ('DND DC Original 106', 'Polish', 'bottle', 'DND', true),
  ('DND DC Original 107', 'Polish', 'bottle', 'DND', true),
  ('DND DC Original 108', 'Polish', 'bottle', 'DND', true),
  ('DND DC Original 109', 'Polish', 'bottle', 'DND', true),
  ('DND DC Original 110', 'Polish', 'bottle', 'DND', true),
  ('DND DC Original 111', 'Polish', 'bottle', 'DND', true),
  ('DND DC Original 112', 'Polish', 'bottle', 'DND', true),
  ('DND DC Original 113', 'Polish', 'bottle', 'DND', true),
  ('DND DC Original 114', 'Polish', 'bottle', 'DND', true),
  ('DND DC Original 115', 'Polish', 'bottle', 'DND', true),
  ('DND DC Original 116', 'Polish', 'bottle', 'DND', true),
  ('DND DC Original 117', 'Polish', 'bottle', 'DND', true),
  ('DND DC Original 118', 'Polish', 'bottle', 'DND', true),
  ('DND DC Original 119', 'Polish', 'bottle', 'DND', true),
  ('DND DC Original 120', 'Polish', 'bottle', 'DND', true),
  ('DND DC Original 121', 'Polish', 'bottle', 'DND', true),
  ('DND DC Original 122', 'Polish', 'bottle', 'DND', true),
  ('DND DC Original 123', 'Polish', 'bottle', 'DND', true),
  ('DND DC Original 124', 'Polish', 'bottle', 'DND', true),
  ('DND DC Original 125', 'Polish', 'bottle', 'DND', true),
  ('DND DC Original 126', 'Polish', 'bottle', 'DND', true),
  ('DND DC Original 127', 'Polish', 'bottle', 'DND', true),
  ('DND DC Original 128', 'Polish', 'bottle', 'DND', true),
  ('DND DC Original 129', 'Polish', 'bottle', 'DND', true),
  ('DND DC Original 130', 'Polish', 'bottle', 'DND', true),
  ('DND DC Original 131', 'Polish', 'bottle', 'DND', true),
  ('DND DC Original 132', 'Polish', 'bottle', 'DND', true),
  ('DND DC Original 133', 'Polish', 'bottle', 'DND', true),
  ('DND DC Original 134', 'Polish', 'bottle', 'DND', true),
  ('DND DC Original 135', 'Polish', 'bottle', 'DND', true),
  ('DND DC Original 136', 'Polish', 'bottle', 'DND', true),
  ('DND DC Original 137', 'Polish', 'bottle', 'DND', true),
  ('DND DC Original 138', 'Polish', 'bottle', 'DND', true),
  ('DND DC Original 139', 'Polish', 'bottle', 'DND', true),
  ('DND DC Original 140', 'Polish', 'bottle', 'DND', true),
  ('DND DC Original 141', 'Polish', 'bottle', 'DND', true),
  ('DND DC Original 142', 'Polish', 'bottle', 'DND', true),
  ('DND DC Original 143', 'Polish', 'bottle', 'DND', true),
  ('DND DC Original 144', 'Polish', 'bottle', 'DND', true)
ON CONFLICT (name) DO NOTHING;

-- ============================================================================
-- DND DC Creamy Series (145-180)
-- ============================================================================
INSERT INTO public.inventory_items (name, category, unit, brand, is_master_item) VALUES
  ('DND DC Creamy 145', 'Polish', 'bottle', 'DND', true),
  ('DND DC Creamy 146', 'Polish', 'bottle', 'DND', true),
  ('DND DC Creamy 147', 'Polish', 'bottle', 'DND', true),
  ('DND DC Creamy 148', 'Polish', 'bottle', 'DND', true),
  ('DND DC Creamy 149', 'Polish', 'bottle', 'DND', true),
  ('DND DC Creamy 150', 'Polish', 'bottle', 'DND', true),
  ('DND DC Creamy 151', 'Polish', 'bottle', 'DND', true),
  ('DND DC Creamy 152', 'Polish', 'bottle', 'DND', true),
  ('DND DC Creamy 153', 'Polish', 'bottle', 'DND', true),
  ('DND DC Creamy 154', 'Polish', 'bottle', 'DND', true),
  ('DND DC Creamy 155', 'Polish', 'bottle', 'DND', true),
  ('DND DC Creamy 156', 'Polish', 'bottle', 'DND', true),
  ('DND DC Creamy 157', 'Polish', 'bottle', 'DND', true),
  ('DND DC Creamy 158', 'Polish', 'bottle', 'DND', true),
  ('DND DC Creamy 159', 'Polish', 'bottle', 'DND', true),
  ('DND DC Creamy 160', 'Polish', 'bottle', 'DND', true),
  ('DND DC Creamy 161', 'Polish', 'bottle', 'DND', true),
  ('DND DC Creamy 162', 'Polish', 'bottle', 'DND', true),
  ('DND DC Creamy 163', 'Polish', 'bottle', 'DND', true),
  ('DND DC Creamy 164', 'Polish', 'bottle', 'DND', true),
  ('DND DC Creamy 165', 'Polish', 'bottle', 'DND', true),
  ('DND DC Creamy 166', 'Polish', 'bottle', 'DND', true),
  ('DND DC Creamy 167', 'Polish', 'bottle', 'DND', true),
  ('DND DC Creamy 168', 'Polish', 'bottle', 'DND', true),
  ('DND DC Creamy 169', 'Polish', 'bottle', 'DND', true),
  ('DND DC Creamy 170', 'Polish', 'bottle', 'DND', true),
  ('DND DC Creamy 171', 'Polish', 'bottle', 'DND', true),
  ('DND DC Creamy 172', 'Polish', 'bottle', 'DND', true),
  ('DND DC Creamy 173', 'Polish', 'bottle', 'DND', true),
  ('DND DC Creamy 174', 'Polish', 'bottle', 'DND', true),
  ('DND DC Creamy 175', 'Polish', 'bottle', 'DND', true),
  ('DND DC Creamy 176', 'Polish', 'bottle', 'DND', true),
  ('DND DC Creamy 177', 'Polish', 'bottle', 'DND', true),
  ('DND DC Creamy 178', 'Polish', 'bottle', 'DND', true),
  ('DND DC Creamy 179', 'Polish', 'bottle', 'DND', true),
  ('DND DC Creamy 180', 'Polish', 'bottle', 'DND', true)
ON CONFLICT (name) DO NOTHING;

-- ============================================================================
-- DND DC Expansion Series (181-326)
-- ============================================================================
INSERT INTO public.inventory_items (name, category, unit, brand, is_master_item) VALUES
  ('DND DC Expansion 181', 'Polish', 'bottle', 'DND', true),
  ('DND DC Expansion 182', 'Polish', 'bottle', 'DND', true),
  ('DND DC Expansion 183', 'Polish', 'bottle', 'DND', true),
  ('DND DC Expansion 184', 'Polish', 'bottle', 'DND', true),
  ('DND DC Expansion 185', 'Polish', 'bottle', 'DND', true),
  ('DND DC Expansion 186', 'Polish', 'bottle', 'DND', true),
  ('DND DC Expansion 187', 'Polish', 'bottle', 'DND', true),
  ('DND DC Expansion 188', 'Polish', 'bottle', 'DND', true),
  ('DND DC Expansion 189', 'Polish', 'bottle', 'DND', true),
  ('DND DC Expansion 190', 'Polish', 'bottle', 'DND', true),
  ('DND DC Expansion 191', 'Polish', 'bottle', 'DND', true),
  ('DND DC Expansion 192', 'Polish', 'bottle', 'DND', true),
  ('DND DC Expansion 193', 'Polish', 'bottle', 'DND', true),
  ('DND DC Expansion 194', 'Polish', 'bottle', 'DND', true),
  ('DND DC Expansion 195', 'Polish', 'bottle', 'DND', true),
  ('DND DC Expansion 196', 'Polish', 'bottle', 'DND', true),
  ('DND DC Expansion 197', 'Polish', 'bottle', 'DND', true),
  ('DND DC Expansion 198', 'Polish', 'bottle', 'DND', true),
  ('DND DC Expansion 199', 'Polish', 'bottle', 'DND', true),
  ('DND DC Expansion 200', 'Polish', 'bottle', 'DND', true),
  ('DND DC Expansion 201', 'Polish', 'bottle', 'DND', true),
  ('DND DC Expansion 202', 'Polish', 'bottle', 'DND', true),
  ('DND DC Expansion 203', 'Polish', 'bottle', 'DND', true),
  ('DND DC Expansion 204', 'Polish', 'bottle', 'DND', true),
  ('DND DC Expansion 205', 'Polish', 'bottle', 'DND', true),
  ('DND DC Expansion 206', 'Polish', 'bottle', 'DND', true),
  ('DND DC Expansion 207', 'Polish', 'bottle', 'DND', true),
  ('DND DC Expansion 208', 'Polish', 'bottle', 'DND', true),
  ('DND DC Expansion 209', 'Polish', 'bottle', 'DND', true),
  ('DND DC Expansion 210', 'Polish', 'bottle', 'DND', true),
  ('DND DC Expansion 211', 'Polish', 'bottle', 'DND', true),
  ('DND DC Expansion 212', 'Polish', 'bottle', 'DND', true),
  ('DND DC Expansion 213', 'Polish', 'bottle', 'DND', true),
  ('DND DC Expansion 214', 'Polish', 'bottle', 'DND', true),
  ('DND DC Expansion 215', 'Polish', 'bottle', 'DND', true),
  ('DND DC Expansion 216', 'Polish', 'bottle', 'DND', true),
  ('DND DC Expansion 217', 'Polish', 'bottle', 'DND', true),
  ('DND DC Expansion 218', 'Polish', 'bottle', 'DND', true),
  ('DND DC Expansion 219', 'Polish', 'bottle', 'DND', true),
  ('DND DC Expansion 220', 'Polish', 'bottle', 'DND', true),
  ('DND DC Expansion 221', 'Polish', 'bottle', 'DND', true),
  ('DND DC Expansion 222', 'Polish', 'bottle', 'DND', true),
  ('DND DC Expansion 223', 'Polish', 'bottle', 'DND', true),
  ('DND DC Expansion 224', 'Polish', 'bottle', 'DND', true),
  ('DND DC Expansion 225', 'Polish', 'bottle', 'DND', true),
  ('DND DC Expansion 226', 'Polish', 'bottle', 'DND', true),
  ('DND DC Expansion 227', 'Polish', 'bottle', 'DND', true),
  ('DND DC Expansion 228', 'Polish', 'bottle', 'DND', true),
  ('DND DC Expansion 229', 'Polish', 'bottle', 'DND', true),
  ('DND DC Expansion 230', 'Polish', 'bottle', 'DND', true),
  ('DND DC Expansion 231', 'Polish', 'bottle', 'DND', true),
  ('DND DC Expansion 232', 'Polish', 'bottle', 'DND', true),
  ('DND DC Expansion 233', 'Polish', 'bottle', 'DND', true),
  ('DND DC Expansion 234', 'Polish', 'bottle', 'DND', true),
  ('DND DC Expansion 235', 'Polish', 'bottle', 'DND', true),
  ('DND DC Expansion 236', 'Polish', 'bottle', 'DND', true),
  ('DND DC Expansion 237', 'Polish', 'bottle', 'DND', true),
  ('DND DC Expansion 238', 'Polish', 'bottle', 'DND', true),
  ('DND DC Expansion 239', 'Polish', 'bottle', 'DND', true),
  ('DND DC Expansion 240', 'Polish', 'bottle', 'DND', true),
  ('DND DC Expansion 241', 'Polish', 'bottle', 'DND', true),
  ('DND DC Expansion 242', 'Polish', 'bottle', 'DND', true),
  ('DND DC Expansion 243', 'Polish', 'bottle', 'DND', true),
  ('DND DC Expansion 244', 'Polish', 'bottle', 'DND', true),
  ('DND DC Expansion 245', 'Polish', 'bottle', 'DND', true),
  ('DND DC Expansion 246', 'Polish', 'bottle', 'DND', true),
  ('DND DC Expansion 247', 'Polish', 'bottle', 'DND', true),
  ('DND DC Expansion 248', 'Polish', 'bottle', 'DND', true),
  ('DND DC Expansion 249', 'Polish', 'bottle', 'DND', true),
  ('DND DC Expansion 250', 'Polish', 'bottle', 'DND', true),
  ('DND DC Expansion 251', 'Polish', 'bottle', 'DND', true),
  ('DND DC Expansion 252', 'Polish', 'bottle', 'DND', true),
  ('DND DC Expansion 253', 'Polish', 'bottle', 'DND', true),
  ('DND DC Expansion 254', 'Polish', 'bottle', 'DND', true),
  ('DND DC Expansion 255', 'Polish', 'bottle', 'DND', true),
  ('DND DC Expansion 256', 'Polish', 'bottle', 'DND', true),
  ('DND DC Expansion 257', 'Polish', 'bottle', 'DND', true),
  ('DND DC Expansion 258', 'Polish', 'bottle', 'DND', true),
  ('DND DC Expansion 259', 'Polish', 'bottle', 'DND', true),
  ('DND DC Expansion 260', 'Polish', 'bottle', 'DND', true),
  ('DND DC Expansion 261', 'Polish', 'bottle', 'DND', true),
  ('DND DC Expansion 262', 'Polish', 'bottle', 'DND', true),
  ('DND DC Expansion 263', 'Polish', 'bottle', 'DND', true),
  ('DND DC Expansion 264', 'Polish', 'bottle', 'DND', true),
  ('DND DC Expansion 265', 'Polish', 'bottle', 'DND', true),
  ('DND DC Expansion 266', 'Polish', 'bottle', 'DND', true),
  ('DND DC Expansion 267', 'Polish', 'bottle', 'DND', true),
  ('DND DC Expansion 268', 'Polish', 'bottle', 'DND', true),
  ('DND DC Expansion 269', 'Polish', 'bottle', 'DND', true),
  ('DND DC Expansion 270', 'Polish', 'bottle', 'DND', true),
  ('DND DC Expansion 271', 'Polish', 'bottle', 'DND', true),
  ('DND DC Expansion 272', 'Polish', 'bottle', 'DND', true),
  ('DND DC Expansion 273', 'Polish', 'bottle', 'DND', true),
  ('DND DC Expansion 274', 'Polish', 'bottle', 'DND', true),
  ('DND DC Expansion 275', 'Polish', 'bottle', 'DND', true),
  ('DND DC Expansion 276', 'Polish', 'bottle', 'DND', true),
  ('DND DC Expansion 277', 'Polish', 'bottle', 'DND', true),
  ('DND DC Expansion 278', 'Polish', 'bottle', 'DND', true),
  ('DND DC Expansion 279', 'Polish', 'bottle', 'DND', true),
  ('DND DC Expansion 280', 'Polish', 'bottle', 'DND', true),
  ('DND DC Expansion 281', 'Polish', 'bottle', 'DND', true),
  ('DND DC Expansion 282', 'Polish', 'bottle', 'DND', true),
  ('DND DC Expansion 283', 'Polish', 'bottle', 'DND', true),
  ('DND DC Expansion 284', 'Polish', 'bottle', 'DND', true),
  ('DND DC Expansion 285', 'Polish', 'bottle', 'DND', true),
  ('DND DC Expansion 286', 'Polish', 'bottle', 'DND', true),
  ('DND DC Expansion 287', 'Polish', 'bottle', 'DND', true),
  ('DND DC Expansion 288', 'Polish', 'bottle', 'DND', true),
  ('DND DC Expansion 289', 'Polish', 'bottle', 'DND', true),
  ('DND DC Expansion 290', 'Polish', 'bottle', 'DND', true),
  ('DND DC Expansion 291', 'Polish', 'bottle', 'DND', true),
  ('DND DC Expansion 292', 'Polish', 'bottle', 'DND', true),
  ('DND DC Expansion 293', 'Polish', 'bottle', 'DND', true),
  ('DND DC Expansion 294', 'Polish', 'bottle', 'DND', true),
  ('DND DC Expansion 295', 'Polish', 'bottle', 'DND', true),
  ('DND DC Expansion 296', 'Polish', 'bottle', 'DND', true),
  ('DND DC Expansion 297', 'Polish', 'bottle', 'DND', true),
  ('DND DC Expansion 298', 'Polish', 'bottle', 'DND', true),
  ('DND DC Expansion 299', 'Polish', 'bottle', 'DND', true),
  ('DND DC Expansion 300', 'Polish', 'bottle', 'DND', true),
  ('DND DC Expansion 301', 'Polish', 'bottle', 'DND', true),
  ('DND DC Expansion 302', 'Polish', 'bottle', 'DND', true),
  ('DND DC Expansion 303', 'Polish', 'bottle', 'DND', true),
  ('DND DC Expansion 304', 'Polish', 'bottle', 'DND', true),
  ('DND DC Expansion 305', 'Polish', 'bottle', 'DND', true),
  ('DND DC Expansion 306', 'Polish', 'bottle', 'DND', true),
  ('DND DC Expansion 307', 'Polish', 'bottle', 'DND', true),
  ('DND DC Expansion 308', 'Polish', 'bottle', 'DND', true),
  ('DND DC Expansion 309', 'Polish', 'bottle', 'DND', true),
  ('DND DC Expansion 310', 'Polish', 'bottle', 'DND', true),
  ('DND DC Expansion 311', 'Polish', 'bottle', 'DND', true),
  ('DND DC Expansion 312', 'Polish', 'bottle', 'DND', true),
  ('DND DC Expansion 313', 'Polish', 'bottle', 'DND', true),
  ('DND DC Expansion 314', 'Polish', 'bottle', 'DND', true),
  ('DND DC Expansion 315', 'Polish', 'bottle', 'DND', true),
  ('DND DC Expansion 316', 'Polish', 'bottle', 'DND', true),
  ('DND DC Expansion 317', 'Polish', 'bottle', 'DND', true),
  ('DND DC Expansion 318', 'Polish', 'bottle', 'DND', true),
  ('DND DC Expansion 319', 'Polish', 'bottle', 'DND', true),
  ('DND DC Expansion 320', 'Polish', 'bottle', 'DND', true),
  ('DND DC Expansion 321', 'Polish', 'bottle', 'DND', true),
  ('DND DC Expansion 322', 'Polish', 'bottle', 'DND', true),
  ('DND DC Expansion 323', 'Polish', 'bottle', 'DND', true),
  ('DND DC Expansion 324', 'Polish', 'bottle', 'DND', true),
  ('DND DC Expansion 325', 'Polish', 'bottle', 'DND', true),
  ('DND DC Expansion 326', 'Polish', 'bottle', 'DND', true)
ON CONFLICT (name) DO NOTHING;

-- ============================================================================
-- DND DC Sheer Series (2436-2471)
-- ============================================================================
INSERT INTO public.inventory_items (name, category, unit, brand, is_master_item) VALUES
  ('DND DC Sheer 2436', 'Polish', 'bottle', 'DND', true),
  ('DND DC Sheer 2437', 'Polish', 'bottle', 'DND', true),
  ('DND DC Sheer 2438', 'Polish', 'bottle', 'DND', true),
  ('DND DC Sheer 2439', 'Polish', 'bottle', 'DND', true),
  ('DND DC Sheer 2440', 'Polish', 'bottle', 'DND', true),
  ('DND DC Sheer 2441', 'Polish', 'bottle', 'DND', true),
  ('DND DC Sheer 2442', 'Polish', 'bottle', 'DND', true),
  ('DND DC Sheer 2443', 'Polish', 'bottle', 'DND', true),
  ('DND DC Sheer 2444', 'Polish', 'bottle', 'DND', true),
  ('DND DC Sheer 2445', 'Polish', 'bottle', 'DND', true),
  ('DND DC Sheer 2446', 'Polish', 'bottle', 'DND', true),
  ('DND DC Sheer 2447', 'Polish', 'bottle', 'DND', true),
  ('DND DC Sheer 2448', 'Polish', 'bottle', 'DND', true),
  ('DND DC Sheer 2449', 'Polish', 'bottle', 'DND', true),
  ('DND DC Sheer 2450', 'Polish', 'bottle', 'DND', true),
  ('DND DC Sheer 2451', 'Polish', 'bottle', 'DND', true),
  ('DND DC Sheer 2452', 'Polish', 'bottle', 'DND', true),
  ('DND DC Sheer 2453', 'Polish', 'bottle', 'DND', true),
  ('DND DC Sheer 2454', 'Polish', 'bottle', 'DND', true),
  ('DND DC Sheer 2455', 'Polish', 'bottle', 'DND', true),
  ('DND DC Sheer 2456', 'Polish', 'bottle', 'DND', true),
  ('DND DC Sheer 2457', 'Polish', 'bottle', 'DND', true),
  ('DND DC Sheer 2458', 'Polish', 'bottle', 'DND', true),
  ('DND DC Sheer 2459', 'Polish', 'bottle', 'DND', true),
  ('DND DC Sheer 2460', 'Polish', 'bottle', 'DND', true),
  ('DND DC Sheer 2461', 'Polish', 'bottle', 'DND', true),
  ('DND DC Sheer 2462', 'Polish', 'bottle', 'DND', true),
  ('DND DC Sheer 2463', 'Polish', 'bottle', 'DND', true),
  ('DND DC Sheer 2464', 'Polish', 'bottle', 'DND', true),
  ('DND DC Sheer 2465', 'Polish', 'bottle', 'DND', true),
  ('DND DC Sheer 2466', 'Polish', 'bottle', 'DND', true),
  ('DND DC Sheer 2467', 'Polish', 'bottle', 'DND', true),
  ('DND DC Sheer 2468', 'Polish', 'bottle', 'DND', true),
  ('DND DC Sheer 2469', 'Polish', 'bottle', 'DND', true),
  ('DND DC Sheer 2470', 'Polish', 'bottle', 'DND', true),
  ('DND DC Sheer 2471', 'Polish', 'bottle', 'DND', true)
ON CONFLICT (name) DO NOTHING;

-- Force PostgREST to reload schema cache
NOTIFY pgrst, 'reload schema';
